# Development overrides for docker-compose.yml
# This file is automatically used by docker-compose when present
# Use this for development with hot reloading and better debugging

version: '3.8'

services:
  # Backend development overrides
  backend:
    build:
      context: ./surfsense_backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./surfsense_backend:/app
      - backend_uploads:/app/uploads
      - backend_podcasts:/app/podcasts
    environment:
      - UVICORN_LOG_LEVEL=debug
    command: ["python", "main.py", "--reload"]

  # Frontend development overrides
  frontend:
    build:
      context: ./surfsense_web
      dockerfile: Dockerfile.dev
    volumes:
      - ./surfsense_web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: ["pnpm", "dev"]

  # Database development overrides (enable logging)
  db:
    command: >
      postgres
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_messages=info
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '